export { Spring } from "./spring";
export { mountBuddy, renderPosterPng } from "./rig";
export type { BuddyMountOptions, BuddyHandle } from "./rig";
export { DEFAULT_CONFIG, resolveConfig } from "./config";
export type { BuddyConfig } from "./config";
export { registerTheme, getTheme, themeNames, resolveTheme, themeFromAccent, makeTheme, glowToHex } from "./themes";
export type { BuddyTheme, ThemeInput, ThemeSpec } from "./themes";
export { FAMILIES, shapePts, shapeDetail, shapeAccent } from "./families";
export type { FamilyName, PlateDef, ShapeKind } from "./families";
export { STATES } from "./states";
export type { BuddyState, BuddyEvent, StateDef } from "./states";
export { CORES, coreNames, traceCore, traceFacets } from "./cores";
export type { CoreShape, CoreDef } from "./cores";
export { BLOB_BODIES, BLOB_EYES, traceBlob, blobAnchors, blobTopR, blobBotR } from "./blob";
export type { BlobBody, BlobEyes } from "./blob";
export { ACCESSORIES, drawAccessory, accessoryAnchor, accessoryLayer, accessoryRank, accessoryRidesHead } from "./accessories";
export type { AccessoryName, AccessoryGeom } from "./accessories";
export { anchorRidesHead } from "./anchors";
export type { Anchor, AnchorName, BodyAnchors, EyeLine } from "./anchors";
export { BLOCK_BUILDS, blockSlabs, blockFigure, traceBlock, traceBlockTorso, traceBlockHead, blockAnchors, blockTopY, blockBotY, blockEyeAnchor, drawBlockBody, drawBlockEyes, applyHeadTransform } from "./block";
export type { BlockBuild, Slab, Chunk, Figure } from "./block";
export { REST_POSE, posture, gestures, LimbRig } from "./block-limbs";
export type { BlockPose, ArmPose, LegPose, HeadPose, PoseInput, Gestures } from "./block-limbs";
export { drawLens } from "./lens";
export type { LensParams } from "./lens";
